extern double FRONT_WHEEL;
extern double SIDE_WHEEL;
extern double X;
extern double Y;
extern double radianHeading;
extern const double horizontalTrackingCenter;
extern const double verticalTrackingCenter;
extern int positionTracking();
void setDrivePosition(double x, double y, double startHeading);
void turnToPosition(double x, double y, vex::directionType dir);
void driveToPosition(double x, double y, vex::directionType dir);
void slowDriveToPosition(double x, double y, vex::directionType dir);
extern double getDistance(double x1, double y1, double x2, double y2);